language: r

sudo: required

cache: packages

os:
  - linux


apt_packages:
##      - doxygen
    - pandoc
    - graphviz
    - librsvg2-dev
    - libmetis-dev
    - libopenblas-base
    - libblas3
    - libatlas-base-dev
    - libblas-dev
    - libopenblas-dev
    - liblapack-dev
    - liblapack3

jobs:
  include:

    - stage: Install package dependencies
      r: 3.5
      install:
        - ./bin/install_dependencies.sh
      script: true

    # - stage: Install package dependencies
    #   r: release
    #   install:
    #     - ./bin/install_dependencies.sh
    #   script: true

    - stage: Install and check the package
      r: 3.5
      install: true
      script:
        - ./bin/install_and_check.sh

    # - stage: Install and check the package
    #   r: release
    #   install: true
    #   script:
    #     - ./bin/install_and_check.sh

    - stage: Run more checks
      r: 3.5
      install: true
      script:
        - ./bin/run_more_checks.sh

    # - stage: Run more checks
    #   r: release
    #   install: true
    #   script:
    #     - ./bin/run_more_checks.sh

    # - stage: Run full example suite
      # r: 3.5
      # install: true
      # script:
      #   - ./bin/run_full_example_suite.sh

##    - stage: Run full example suite
##      r: release
##      install: true
##      script:
##        - ./bin/run_full_example_suite.sh

    # - stage: Build and deploy documentation
    #   r: release
    #   install:
    #     - wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.linux.bin.tar.gz
    #     - tar zxf doxygen-1.8.12.linux.bin.tar.gz
    #     - export PATH=`pwd`/doxygen-1.8.12/bin:$PATH
    #     - doxygen -v
    #   script:
    #     - make doxygen
    #     - ./bin/deploy.sh

notifications:
  email:
    on_success: never
    on_failure: never

